version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - tgfischer
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: react-bootstrap
    versions:
    - 1.5.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.3
  - dependency-name: "@storybook/addons"
    versions:
    - 6.2.7
    - 6.2.8
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.8
  - dependency-name: babel-loader
    versions:
    - 8.2.2
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/yup"
    versions:
    - 0.29.11
  - dependency-name: formik
    versions:
    - 2.2.6
  - dependency-name: classnames
    versions:
    - 2.3.1
  - dependency-name: yup
    versions:
    - 0.32.9
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: style-loader
    versions:
    - 2.0.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.7
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
    - 7.23.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: react-is
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: react
    versions:
    - 16.14.0
  - dependency-name: prettier
    versions:
    - 2.2.1
